language: node_js
node_js:
  - 'stable'
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  name: Deployment Travis Bot
  on:
    branch: master
after_deploy:
  - npm run build